### PR TITLE
Add category view of the archive

### PR DESCRIPTION
**Pull request by tomliversidge**
My motivation for this pull request was wanting to see the articles by their categories (i.e. "show me all the articles related to code reviews")

If accepted, this pull request will:

- add a categories page that displays a list of categories and all posts for that category
- adds a link from article's categories text to the categories page

For this to work, a list of categories must be maintained (_data/categories.yml). Unfortunately it doesn't look like github pages supports auto-generating this list. Hopefully this isn't too hard to maintain.

### CODE REVIEW

**Comment by tomliversidge** [comment]
Should look like this:

capture

**Comment by tomliversidge** [comment]
Actually it turns out you can just generate the categories list without needing a .yml file. You just need 

{% for category in site.categories %}

-- stuff here

{% endif %}

I can look at updating this if it is something you think is worthwhile adding to the site

thanks

**Comment by gvwilson** [comment]
Yes please - sorry I haven't had a chance to merge this yet.

**Comment by tomliversidge** [comment]
Thanks Greg - last two commits should auto generate the category page from the meta information in the posts

Cheers
Tom

**Pull request merged**
